[Web Onboarding Project Task 2] Supabase Integrations
nehaahussain/blueprint-onboarding pull request #3
Opened 2024-10-09 21:47 UTC by nehaahussain

[//]: # "Feel free to customize this template to your project's vibes"

## What's new in this PR
####  Populated the post screen with data from the supabase table. Also includes the updated code from addressed comments in task 1.

## Screenshots
<img width="240" alt="Screenshot 2024-10-01 at 12 58 13 PM" src="https://github.com/user-attachments/assets/c1d7ba01-ee9a-4a68-a6c3-1108fd87c6c0">

## Next steps
#### The output is the loading screen for less than a second then just a blank screen. I've tried debugging but can't seem to figure out the issue as I used the template. Just wanted to create a PR of the progress so far.

CC: @insert pl github username here

2024-10-14 17:46 UTC, ronniebeggs requested changes
Once you fix your environment variables, you should be able to see supabase data imported into your project. You're the right track! Good job!

2024-10-14 17:46 UTC, ronniebeggs commented on supabase/client.ts
> +);
Try adding the `NEXT_` prefix to each of your environment variables. I should've pointed this out earlier, but it seems that environment variables are only accessible to NextJs applications running in the browser if this prefix is includes ([docs here](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser)).

2024-10-14 17:46 UTC, ronniebeggs commented on app/styles.module.css
> +}
This is one way to offset the like and username text. For flex boxes, we can alternatively apply a `column-gap` attribute, which I believe is a bit cleaner.

2024-10-14 17:46 UTC, ronniebeggs commented on app/styles.module.css
> +  padding-bottom: 3%;
Just out of curiosity, where did these values come from?

2024-10-15 21:55 UTC, nehaahussain commented on app/styles.module.css
> +  padding-bottom: 3%;
`line-height: 138.462%;` is from the figma and `padding-bottom: 3%;` is from chatgpt.

2024-10-24 22:23 UTC, merged